---
- name: Template seed list
  template: src=seeds.j2 dest=/tmp/seed_list mode=0664

- name: Load seed list
  shell: cat /tmp/seed_list
  register: seed_list

- name: Set seeds fact
  set_fact: seeds={{ seed_list.stdout }}

#- debug: var=seeds
#- debug: msg="{{ seeds }}"
