---
- name: Add a DataStax repository file
  lineinfile:
    name: "{{ dse_repo_file }}"
    create: yes
    regexp: 'debian\.datastax\.com\/enterprise'
    line: "deb https://debian.datastax.com/enterprise stable main"
    state: present

- name: Add the DataStax repository key
  apt_key: 
    url: "https://debian.datastax.com/debian/repo_key"
    state: present
